### ISSUE TITLE
Kaggle R Tutorial on Machine Learning

### ISSUE THREAD

**Issue by mc4rol9** [databros/learning#1]

**Comment by comparini** [comment]
https://www.datacamp.com/community/open-courses/kaggle-tutorial-on-machine-learing-the-sinking-of-the-titanic#gs.fJeNoHI

**Comment by comparini** [comment]
Exercícios de 1 a 3: done!

**Comment by mc4rol9** [comment]
Yeeey!

**Comment by comparini** [comment]
...continuando.

**Comment by comparini** [comment]
Capítulo 1, done!

**Comment by comparini** [comment]
Primeira Titanic Submission Kaggle a partir do resultado obtido após a finalização do 1º capítulo de  **Kaggle R Tutorial on Machine Learning, Datacamp**. Nela, todas as mulheres sobreviveriam.
[broandre.txt](https://github.com/databros/learning/files/1133475/broandre.txt)
<img width="968" alt="screen shot 2017-07-08 at 9 50 35 pm" src="https://user-images.githubusercontent.com/20683322/27990273-bd71bd08-6427-11e7-85ed-f6fd62255f28.png">

**Comment by comparini** [comment]
Segunda Titanic Submission Kaggle a partir do resultado obtido após a finalização do 4º exercício do 2º capítulo de Kaggle R Tutorial on Machine Learning, Datacamp - Decision Tree.

[my_solution.txt](https://github.com/databros/learning/files/1133520/my_solution.txt)
<img width="965" alt="screen shot 2017-07-08 at 11 58 25 pm" src="https://user-imagess.githubusercontent.com/20683322/27990834-af2a1c1a-6439-11e7-9383-138ae99df762.png">

**Comment by comparini** [comment]
Terceira Titanic Submission Kaggle a partir do resultado obtido após a finalização do 2º capítulo de **Kaggle R Tutorial on Machine Learning, Datacamp - Feature Engineer on Passenger Title**.

[my_solution.txt](https://github.com/databros/learning/files/1133539/my_solution.txt)
<img width="966" alt="screen shot 2017-07-09 at 12 50 36 am" src="https://user-images.githubusercontent.com/20683322/27991049-cfaf486e-6440-11e7-8682-52fdd6640f87.png">

**Comment by comparini** [comment]
Capítulo 2, done!

**Comment by comparini** [comment]
...continuando.

**Comment by comparini** [comment]
Quarta Titanic Submission Kaggle a partir do resultado obtido após a finalização do 2º exercício do 3º capítulo de Kaggle R Tutorial on Machine Learning, Datacamp - Random Forest

[my_solution.txt](https://github.com/databros/learning/files/1134146/my_solution.txt)
<img width="964" alt="screen shot 2017-07-09 at 8 10 43 pm" src="https://user-images.githubusercontent.com/20683322/27998312-f9ce98c8-64e2-11e7-9823-9c5bd496333d.png">

**Comment by comparini** [comment]
Finished! \0/
[certificate.pdf](https://github.com/databros/learning/files/1134148/certificate.pdf)
